- server/.env
Added my name to the .env file
> added jimmy to .env file

- server/.env
> Added my name to .env file

- server/.env
- server/app.js
- server/config/db.js
- server/package-lock.json
- server/package.json
> Mongo configure

- client/package-lock.json
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
removed incorret back end socket.io package, and added `npm run dev` to project root, running both server and client
> Remove incorrect backend socketio package

- client/.eslintrc.json
- client/package.json
- client/src/App.js
- server/.eslintrc.json
- server/app.js
- server/bin/www
- server/package-lock.json
- server/package.json
- server/routes/index.js
- server/routes/ping.js
- server/websocket/index.js
Some quality of life updates. I was running into issues with Nodemon restarting itself before closing the port it was using, should be fixed now but let me know if you run into issues.
You can type `rs` right into the terminal to manually restart the backend server
I separated the backend socket into its own file so we can write all our handler functions there.
Ping socket button on frontend working with garbage data. We'll need to reorganize and most likely have a frontend websocket client.
> Socket testing

- server/config/passport-config.js
- server/models/User.js
- server/package-lock.json
- server/routes/user.js
Completed the backbone of local passport register method
> Passport local register

- server/controllers/InvitationController.js
- server/models/Invitation.js
- server/models/User.js
- server/package-lock.json
#21 Template for invitation model & controller
> Boilerplate for invitation model & controller

- client/src/App.js
- client/src/components/profile/profile.component.jsx
- client/src/components/search-field/search-field.component.jsx
- client/src/components/sidebar/sidebar.component.jsx
- client/src/components/tabs-panel/tabs-panel.component.jsx
- client/src/pages/dashboard/dashboard.component.jsx
- client/src/themes/theme.js
partially completed sidebar related to issue #15 
currently hardcoded just proof of concept, no state yet.
> Front End Dashboard Interface day 1 merge

- client/package-lock.json
- client/src/pages/login/Login.js
- server/package-lock.json
- server/routes/index.js
- server/routes/ping.js
#12 Polished login page (not complete)
> Refactored login page

- client/src/pages/login/Login.js
> Changed theme color

- client/package-lock.json
- client/src/pages/userform/Login.js
- client/src/pages/userform/Register.js
- client/src/pages/userform/userFunctions.js
- client/src/utils/HTTPClient.js
- client/src/websocketTesting.js
- server/controllers/ChatroomController.js
- server/controllers/MessageController.js
- server/controllers/UserController.js
- server/package-lock.json
- server/routes/userRoutes.js
- server/websocket/index.js
> Login register

- client/src/components/chat-header/chat-header.component.jsx
- client/src/components/invite-friend-backdrop/invite-friend-backdrop.styles.jsx
- client/src/components/profile/profile-as-button.container.jsx
- client/src/components/profile/profile.styles.jsx
- client/src/pages/dashboard/dashboard.component.jsx
applies a few code review suggestions from #42
> Feature  dashboard

- client/src/websocketTesting.js
- server/controllers/ChatroomController.js
- server/controllers/InvitationController.js
- server/controllers/MessageController.js
- server/controllers/UserController.js
- server/models/Invitation.js
- server/routes/userRoutes.js
- server/websocket/index.js
#24 Send invitation & Accept invitation
> Sent invitation & accept it

- client/src/pages/userform/Login.js
- client/src/pages/userform/Register.js
Fixed some of the warnings that appear in login and register pages
> fix some warnings that occur in login / register page

- client/src/websocketTesting.js
- server/controllers/InvitationController.js
- server/controllers/UserController.js
- server/models/Invitation.js
- server/package-lock.json
- server/package.json
- server/routes/userRoutes.js
- server/services/mailService.js
- server/websocket/index.js
Added sendgrid & prevent from friends creating invitation to each other
> Added sendgrid & prevent from friends creating invitation to each other

- .gitignore
- client/src/pages/userform/Register.js
- client/src/websocketTesting.js
- server/controllers/InvitationController.js
- server/models/Invitation.js
- server/package-lock.json
- server/package.json
- server/routes/userRoutes.js
- server/services/mailService.js
- server/services/translateService.js
- server/websocket/index.js
- server/websocket/sendMsg.js
#67 translation message being saved
> Translation message saving + added field in Register paage

- client/src/components/invite-friend-backdrop/invite-friend-backdrop.component.jsx
- client/src/components/profile/profile.component.jsx
- client/src/components/sidebar-tab-panel-invites/sidebar-tab-panel-invites.component.jsx
- client/src/components/sidebar/sidebar.component.jsx
- client/src/pages/dashboard/dashboard.component.jsx
- server/controllers/ChatroomController.js
- server/controllers/InvitationController.js
- server/controllers/UserController.js
- server/routes/userRoutes.js
- server/services/formatDataService.js
- server/services/mailService.js
- server/websocket/index.js
> Sends invitation email to a friend

- server/controllers/ChatroomController.js
- server/controllers/UserController.js
- server/services/seedDataService.js
- server/websocket/index.js
Users can now chat after accepting the friend request / invitation
> Users can now chat after accepting friend request

- server/controllers/ChatroomController.js
- server/controllers/MessageController.js
- server/websocket/index.js
- server/websocket/sendMsg.js
Promise rejection error handling
> Promise rejection handling in 'sendMsg'

- client/src/components/chat-message/chat-message.styles.jsx
- client/src/components/sidebar/sidebar.component.jsx
- client/src/components/user-profile/user-profile.component.jsx
- server/models/User.js
- server/routes/userRoutes.js
added a gradiant to chat bubble #82 
logout button now works #83
> Feature visual fluff

- client/src/components/chat-message/chat-message.styles.jsx
- client/src/components/message-field/message-field.component.jsx
#89 
also fixed a bug from #92 which caused the message bubble to not render correctly
> Feature  draft messages in storage

- client/src/components/profile-backdrop/profile-backdrop.component.jsx
- client/src/components/profile-pic-uploader/profile-pic-uploader.component.jsx
- client/src/components/sidebar/sidebar.component.jsx
- client/src/pages/dashboard/dashboard.component.jsx
- server/aws/aws-utils.js
- server/controllers/UserController.js
- server/routes/userRoutes.js
- server/websocket/index.js
- server/websocket/profilePic.js
#91 
also added profile picture cleanup when you change the picture
> Feature emit PFP(profile pic) when updating PFP

- client/src/App.js
- client/src/components/invite-friend-backdrop/invite-friend-backdrop.component.jsx
- client/src/pages/dashboard/dashboard.component.jsx
- client/src/pages/userform/Login.js
- client/src/pages/userform/Register.js
- server/controllers/UserController.js
- server/models/User.js
- server/routes/inviteRoutes.js
- server/routes/userRoutes.js
- server/services/bcryptService.js
#66 users can now invite each other through invitation referral url
> Invite user by referral link

- .circleci/config.yml
- server/app.js
testing deployment. by merging this to master
> deployment preparations 1

- .circleci/config.yml
- server/app.js
Reverts hatchways/team-mint-oreo#107
> Revert "deployment preparations 1"

- client/package-lock.json
- client/package.json
trying to fix heroku build crashing
> moved eslint to dev dependancies

- client/package-lock.json
- client/package.json
- client/src/pages/dashboard/dashboard.component.jsx
- client/src/websocketTesting.js
- server/app.js
attempt to fix improper display
> Deployment prep
